### ISSUE TITLE
dots in interface names problematic?

### ISSUE THREAD

**Issue by job** [ypconfig/ypconfig#8]
on 1.0.2

```
root@dcg-1:~# ypconfig createconfig
Traceback (most recent call last):
  File "/usr/local/bin/ypconfig", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/ypconfig/cli.py", line 68, in main
    cfg = config.Validate(cfg)
  File "/usr/local/lib/python3.5/dist-packages/ypconfig/config.py", line 238, in Validate
    document[iface] = Interface(document[iface], iface)
  File "/usr/local/lib/python3.5/dist-packages/ypconfig/config.py", line 128, in Interface
    ret['name'] = Ifname(iname)
  File "/usr/local/lib/python3.5/dist-packages/ypconfig/config.py", line 81, in Ifname
    raise ValueError("Invalid interfacename: %s" % (teststring))
ValueError: Invalid interfacename: eth7.108
root@dcg-1:~#
```

**Comment by tuxis-ie** [comment]
Obviously! Vlanid and parent!
